// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLtext.Models;

namespace SQLtext.Migrations
{
    [DbContext(typeof(longtermcareContext))]
    [Migration("20230530080702_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SQLtext.Models.CarPick", b =>
                {
                    b.Property<string>("CarId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Car_ID");

                    b.Property<string>("CarCaseAdr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Car_CaseAdr");

                    b.Property<DateTime>("CarDate")
                        .HasColumnType("date")
                        .HasColumnName("Car_Date");

                    b.Property<double>("CarKm")
                        .HasColumnType("float")
                        .HasColumnName("Car_Km");

                    b.Property<double>("CarL")
                        .HasColumnType("float")
                        .HasColumnName("Car_L");

                    b.Property<DateTime>("CarMonth")
                        .HasColumnType("date")
                        .HasColumnName("Car_Month");

                    b.Property<string>("CarNum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Car_Num");

                    b.Property<decimal>("CarPrice")
                        .HasColumnType("money")
                        .HasColumnName("Car_Price");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Car_Type");

                    b.Property<string>("CaseContId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_ContID");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CarId")
                        .HasName("PK__car_pick__523653D98367FCC5");

                    b.HasIndex("CaseContId");

                    b.HasIndex("MemSid");

                    b.ToTable("car_pick");
                });

            modelBuilder.Entity("SQLtext.Models.CaseAct", b =>
                {
                    b.Property<string>("ActId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Act_ID");

                    b.Property<string>("ActCourse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Act_Course");

                    b.Property<DateTime>("ActDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Act_Date");

                    b.Property<string>("ActLec")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Act_Lec");

                    b.Property<string>("ActLoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Act_Loc");

                    b.Property<string>("ActSer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Act_Ser");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.HasKey("ActId")
                        .HasName("PK__case_act__6564ADDDE6E88FEE");

                    b.HasIndex("CaseNo");

                    b.ToTable("case_act");
                });

            modelBuilder.Entity("SQLtext.Models.CaseCareRecord", b =>
                {
                    b.Property<string>("CaseQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_QAID");

                    b.Property<string>("CaseCont")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Case_Cont");

                    b.Property<string>("CaseIssue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Issue");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<DateTime>("CaseRegTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_RegTime");

                    b.Property<string>("CaseRem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Rem");

                    b.Property<DateTime>("CaseTime1")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_Time1");

                    b.Property<DateTime>("CaseTime2")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_Time2");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CaseQaid")
                        .HasName("PK__Case_Car__21B54A27F2CCAA90");

                    b.HasIndex("CaseNo");

                    b.HasIndex("MemSid");

                    b.ToTable("Case_Care_Records");
                });

            modelBuilder.Entity("SQLtext.Models.CaseDailyRegistration", b =>
                {
                    b.Property<string>("CaseContId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_ContID");

                    b.Property<string>("CaseCont")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Case_Cont");

                    b.Property<DateTime>("CaseDailyTime1")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_dailyTime1");

                    b.Property<DateTime>("CaseDailyTime2")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_dailyTime2");

                    b.Property<string>("CaseIssue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Issue");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CasePick")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Case_Pick");

                    b.Property<int>("CasePluse")
                        .HasColumnType("int")
                        .HasColumnName("Case_Pluse");

                    b.Property<DateTime>("CaseRegTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_RegTime");

                    b.Property<string>("CaseRem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Rem");

                    b.Property<int>("CaseTemp")
                        .HasColumnType("int")
                        .HasColumnName("Case_Temp");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CaseContId")
                        .HasName("PK__case_dai__0D7D6BC7A01B2B94");

                    b.HasIndex("CaseNo");

                    b.HasIndex("MemSid");

                    b.ToTable("case_daily_registration");
                });

            modelBuilder.Entity("SQLtext.Models.CaseInfor", b =>
                {
                    b.Property<string>("CaseNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CaseActv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Actv");

                    b.Property<string>("CaseAddr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Addr");

                    b.Property<DateTime>("CaseBd")
                        .HasColumnType("date")
                        .HasColumnName("Case_BD");

                    b.Property<string>("CaseCntAdd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_CntAdd");

                    b.Property<string>("CaseCntRel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_CntRel");

                    b.Property<string>("CaseCntTel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_CntTel");

                    b.Property<string>("CaseCnta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Cnta");

                    b.Property<string>("CaseDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Desc");

                    b.Property<string>("CaseEdu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Edu");

                    b.Property<string>("CaseFactly")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Factly");

                    b.Property<string>("CaseFami")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Fami");

                    b.Property<string>("CaseFund")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Fund");

                    b.Property<string>("CaseGender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Gender");

                    b.Property<string>("CaseHealth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Health");

                    b.Property<string>("CaseHouse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_House");

                    b.Property<string>("CaseIdcard")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Case_IDcard");

                    b.Property<string>("CaseIdent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Ident");

                    b.Property<string>("CaseLang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Lang");

                    b.Property<string>("CaseMari")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Mari");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Name");

                    b.Property<string>("CasePassword")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Password");

                    b.Property<string>("CaseProf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Prof");

                    b.Property<string>("CaseQues")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Ques");

                    b.Property<string>("CaseRegName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_RegName");

                    b.Property<string>("CaseRegTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_RegTime");

                    b.Property<string>("CaseRelig")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Relig");

                    b.Property<string>("CaseSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Source");

                    b.Property<string>("CaseUnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_UnitName");

                    b.Property<string>("CaseUnitNum")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_UnitNum");

                    b.Property<string>("CaseWork")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_Work");

                    b.HasKey("CaseNo")
                        .HasName("PK__case_inf__D0610232CD08B242");

                    b.ToTable("case_infor");
                });

            modelBuilder.Entity("SQLtext.Models.CaseNeed", b =>
                {
                    b.Property<string>("CaseNeedId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_NeedID");

                    b.Property<string>("CaseAct")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Act");

                    b.Property<string>("CaseCare")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Care");

                    b.Property<string>("CaseCons")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Cons");

                    b.Property<string>("CaseEat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Eat");

                    b.Property<string>("CaseFami")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Fami");

                    b.Property<string>("CaseHear")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Hear");

                    b.Property<string>("CaseMed")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Med");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<string>("CaseRead")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Read");

                    b.Property<string>("CaseSee")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_See");

                    b.Property<string>("CaseSpeak")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Speak");

                    b.Property<string>("CaseView1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View1");

                    b.Property<string>("CaseView2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View2");

                    b.Property<string>("CaseView3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View3");

                    b.Property<string>("CaseView4")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View4");

                    b.Property<string>("CaseView5")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View5");

                    b.Property<string>("CaseView6")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View6");

                    b.Property<string>("CaseView7")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View7");

                    b.Property<string>("CaseView8")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View8");

                    b.Property<string>("CaseView9")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Case_View9");

                    b.HasKey("CaseNeedId");

                    b.HasIndex("CaseNo");

                    b.ToTable("Case_Need");
                });

            modelBuilder.Entity("SQLtext.Models.CasePhysicalMental", b =>
                {
                    b.Property<string>("CaseQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_QAID");

                    b.Property<string>("CaseContent1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content1");

                    b.Property<string>("CaseContent10")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content10");

                    b.Property<string>("CaseContent11")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content11");

                    b.Property<string>("CaseContent12")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content12");

                    b.Property<string>("CaseContent13")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content13");

                    b.Property<string>("CaseContent2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content2");

                    b.Property<string>("CaseContent3")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content3");

                    b.Property<string>("CaseContent4")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content4");

                    b.Property<string>("CaseContent5")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content5");

                    b.Property<string>("CaseContent6")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content6");

                    b.Property<string>("CaseContent7")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content7");

                    b.Property<string>("CaseContent8")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content8");

                    b.Property<string>("CaseContent9")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Case_Content9");

                    b.Property<string>("CaseFre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Fre");

                    b.Property<string>("CaseLive")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Live");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.HasKey("CaseQaid")
                        .HasName("PK__case_phy__21B54A27A45929E0");

                    b.HasIndex("CaseNo");

                    b.ToTable("case_physical_mental");
                });

            modelBuilder.Entity("SQLtext.Models.CaseTelRecord", b =>
                {
                    b.Property<string>("CaseTelQaid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_TelQAID");

                    b.Property<string>("CaseAns")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Ans");

                    b.Property<string>("CaseCom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Case_Com");

                    b.Property<string>("CaseExp")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Exp");

                    b.Property<string>("CaseFam")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Fam");

                    b.Property<string>("CaseHea")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Hea");

                    b.Property<string>("CaseLive")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Live");

                    b.Property<string>("CaseMental")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_Mental");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Case_No");

                    b.Property<DateTime>("CaseRegTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_RegTime");

                    b.Property<string>("CaseSick")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Case_Sick");

                    b.Property<DateTime>("CaseTelTime1")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_TelTime1");

                    b.Property<DateTime>("CaseTelTime2")
                        .HasColumnType("datetime")
                        .HasColumnName("Case_TelTime2");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("CaseTelQaid")
                        .HasName("PK__Case_Tel__8C289C65ED256F69");

                    b.HasIndex("CaseNo");

                    b.HasIndex("MemSid");

                    b.ToTable("Case_Tel_Records");
                });

            modelBuilder.Entity("SQLtext.Models.LectureClass", b =>
                {
                    b.Property<string>("SchWeek")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sch_Week");

                    b.Property<string>("SchAm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_Am");

                    b.Property<string>("SchPm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Sch_Pm");

                    b.HasKey("SchWeek")
                        .HasName("PK__lecture___CE91D8F57C0189BF");

                    b.ToTable("lecture_class");
                });

            modelBuilder.Entity("SQLtext.Models.LectureTable", b =>
                {
                    b.Property<string>("LecId")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Lec_ID");

                    b.Property<string>("LecAim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lec_Aim");

                    b.Property<string>("LecClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Class");

                    b.Property<DateTime>("LecDate")
                        .HasColumnType("date")
                        .HasColumnName("Lec_Date");

                    b.Property<string>("LecLeader")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Leader");

                    b.Property<string>("LecPla")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Pla");

                    b.Property<string>("LecStep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lec_Step");

                    b.Property<string>("LecTheme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Lec_Theme");

                    b.Property<string>("LecTool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Lec_Tool");

                    b.Property<string>("MemSid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.HasKey("LecId")
                        .HasName("PK__lecture___2E5B8E905793C8AC");

                    b.HasIndex("MemSid");

                    b.ToTable("lecture_table");
                });

            modelBuilder.Entity("SQLtext.Models.MemberInformation", b =>
                {
                    b.Property<string>("MemSid")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_SID");

                    b.Property<string>("MemAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Address");

                    b.Property<DateTime>("MemBd")
                        .HasColumnType("date")
                        .HasColumnName("Mem_BD");

                    b.Property<string>("MemCert")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Cert");

                    b.Property<string>("MemEdu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Edu");

                    b.Property<string>("MemExpr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Expr");

                    b.Property<string>("MemGender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_Gender");

                    b.Property<string>("MemIdent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Ident");

                    b.Property<string>("MemMovt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Movt");

                    b.Property<string>("MemMphone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Mem_MPhone");

                    b.Property<string>("MemName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_Name");

                    b.Property<string>("MemPassword")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_Password");

                    b.Property<string>("MemProf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Prof");

                    b.Property<string>("MemPserv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_PServ");

                    b.Property<string>("MemSerRec")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_SerRec");

                    b.Property<string>("MemSite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Mem_Site");

                    b.Property<string>("MemTphone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("Mem_Tphone");

                    b.Property<string>("MemTrans")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mem_Trans");

                    b.Property<string>("MemUid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Mem_UID");

                    b.Property<string>("MemUnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Mem_UnitName");

                    b.Property<string>("MemUnitNum")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Mem_UnitNum");

                    b.HasKey("MemSid")
                        .HasName("PK__Member_I__47D0834AC937CAE3");

                    b.ToTable("Member_Information");
                });

            modelBuilder.Entity("SQLtext.Models.CarPick", b =>
                {
                    b.HasOne("SQLtext.Models.CaseDailyRegistration", "CaseCont")
                        .WithMany("CarPicks")
                        .HasForeignKey("CaseContId")
                        .HasConstraintName("FK__car_pick__Case_C__45F365D3")
                        .IsRequired();

                    b.HasOne("SQLtext.Models.MemberInformation", "MemS")
                        .WithMany("CarPicks")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__car_pick__Mem_SI__44FF419A")
                        .IsRequired();

                    b.Navigation("CaseCont");

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("SQLtext.Models.CaseAct", b =>
                {
                    b.HasOne("SQLtext.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseActs")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__case_act__Case_N__2C3393D0")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("SQLtext.Models.CaseCareRecord", b =>
                {
                    b.HasOne("SQLtext.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseCareRecords")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Care__Case___2F10007B")
                        .IsRequired();

                    b.HasOne("SQLtext.Models.MemberInformation", "MemS")
                        .WithMany("CaseCareRecords")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__Case_Care__Mem_S__300424B4")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("SQLtext.Models.CaseDailyRegistration", b =>
                {
                    b.HasOne("SQLtext.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseDailyRegistrations")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__case_dail__Case___32E0915F")
                        .IsRequired();

                    b.HasOne("SQLtext.Models.MemberInformation", "MemS")
                        .WithMany("CaseDailyRegistrations")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__case_dail__Mem_S__33D4B598")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("SQLtext.Models.CaseNeed", b =>
                {
                    b.HasOne("SQLtext.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseNeeds")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Need__Case___36B12243")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("SQLtext.Models.CasePhysicalMental", b =>
                {
                    b.HasOne("SQLtext.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CasePhysicalMentals")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__case_phys__Case___398D8EEE")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");
                });

            modelBuilder.Entity("SQLtext.Models.CaseTelRecord", b =>
                {
                    b.HasOne("SQLtext.Models.CaseInfor", "CaseNoNavigation")
                        .WithMany("CaseTelRecords")
                        .HasForeignKey("CaseNo")
                        .HasConstraintName("FK__Case_Tel___Case___3C69FB99")
                        .IsRequired();

                    b.HasOne("SQLtext.Models.MemberInformation", "MemS")
                        .WithMany("CaseTelRecords")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__Case_Tel___Mem_S__3D5E1FD2")
                        .IsRequired();

                    b.Navigation("CaseNoNavigation");

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("SQLtext.Models.LectureTable", b =>
                {
                    b.HasOne("SQLtext.Models.MemberInformation", "MemS")
                        .WithMany("LectureTables")
                        .HasForeignKey("MemSid")
                        .HasConstraintName("FK__lecture_t__Mem_S__4222D4EF")
                        .IsRequired();

                    b.Navigation("MemS");
                });

            modelBuilder.Entity("SQLtext.Models.CaseDailyRegistration", b =>
                {
                    b.Navigation("CarPicks");
                });

            modelBuilder.Entity("SQLtext.Models.CaseInfor", b =>
                {
                    b.Navigation("CaseActs");

                    b.Navigation("CaseCareRecords");

                    b.Navigation("CaseDailyRegistrations");

                    b.Navigation("CaseNeeds");

                    b.Navigation("CasePhysicalMentals");

                    b.Navigation("CaseTelRecords");
                });

            modelBuilder.Entity("SQLtext.Models.MemberInformation", b =>
                {
                    b.Navigation("CarPicks");

                    b.Navigation("CaseCareRecords");

                    b.Navigation("CaseDailyRegistrations");

                    b.Navigation("CaseTelRecords");

                    b.Navigation("LectureTables");
                });
#pragma warning restore 612, 618
        }
    }
}
